### PR TITLE
Replace "Open" with "Update" on update screen

### PR DESCRIPTION
**Pull request by Petrprogs**

### CODE REVIEW

**Comment by Feodor0090** [comment]
That's an interesting case.

If you check how it works, it's not difficult to see that "update" system is actually a telemetry reporter, which send you model, version and functions which you used and receives an <ins>arbitrary</ins> text/url to show. <ins>One (not single)</ins> use case of this - check your version server-side and return update prompt. So "Open" button is here to cover <i>other</i> cases, since "open" is the most universal text for such button.

Anyways, MMaps are running for ~3 monthes already and we still didn't need to use this for anything but update prompts. So, may be it really worth to apply this... Maybe not... Dunno.

**Comment by Petrprogs** [comment]
The final decision is yours :)

**Comment by Feodor0090** [comment]
@shinovon decide something here

**Review by Feodor0090 — APPROVED** [review]
2 weeks passed and i still have no idea how we can use this for anything else but updates. Merging because why not.

**Pull request merged**
